package aop;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Noe
 */
public class RegisterView extends javax.swing.JFrame {

    int xx, xy;
    
    public RegisterView() {
        initComponents();
        
        pnl_overlay.setBackground(new Color(0,0,0,200));
        ImageIcon head = new ImageIcon(getClass().getResource("/images/imgRegister.jpg"));
        imgRegister.setIcon(scaleImageFill(head, imgRegister));
        
    }
    
    // Escalando Imagenes
    public ImageIcon scaleImageFill(ImageIcon imgi, JLabel jl){
        int iconWidth = imgi.getIconWidth();
        int iconHeight = imgi.getIconHeight();
        
        double scaleFactor = Math.min(1d, getScaleFactorToFill(new Dimension(iconWidth, iconHeight), jl.getSize()));

        int scaleWidth = (int) Math.round(iconWidth * scaleFactor);
        int scaleHeight = (int) Math.round(iconHeight * scaleFactor);

        Image scaled = imgi.getImage().getScaledInstance(scaleWidth, scaleHeight, Image.SCALE_SMOOTH);
        ImageIcon iconf = new ImageIcon(scaled);
        return iconf;
    }
    
    public double getScaleFactor(int iMasterSize, int iTargetSize) {
        double dScale = 1;
        if (iMasterSize > iTargetSize) {
            dScale = (double) iTargetSize / (double) iMasterSize;
        } else {
            dScale = (double) iTargetSize / (double) iMasterSize;
        }
        return dScale;
    }

    public double getScaleFactorToFit(Dimension original, Dimension toFit) {
        double dScale = 1d;
        if (original != null && toFit != null) {
            double dScaleWidth = getScaleFactor(original.width, toFit.width);
            double dScaleHeight = getScaleFactor(original.height, toFit.height);

            dScale = Math.min(dScaleHeight, dScaleWidth);
        }
        return dScale;
    }
    
    public double getScaleFactorToFill(Dimension masterSize, Dimension targetSize) {
        double dScaleWidth = getScaleFactor(masterSize.width, targetSize.width);
        double dScaleHeight = getScaleFactor(masterSize.height, targetSize.height);

        double dScale = Math.max(dScaleHeight, dScaleWidth);

        return dScale;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitlebar = new javax.swing.JPanel();
        exitLogin = new javax.swing.JLabel();
        minLogin = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        pnl_overlay = new javax.swing.JPanel();
        imgRegister = new javax.swing.JLabel();
        pnlRegister = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        nameR = new javax.swing.JTextField();
        s1 = new javax.swing.JSeparator();
        emailL = new javax.swing.JLabel();
        emailR = new javax.swing.JTextField();
        s2 = new javax.swing.JSeparator();
        psswdL = new javax.swing.JLabel();
        psswdR = new javax.swing.JPasswordField();
        s3 = new javax.swing.JSeparator();
        phoneL = new javax.swing.JLabel();
        phoneR = new javax.swing.JTextField();
        s4 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        postalL = new javax.swing.JLabel();
        postalR = new javax.swing.JTextField();
        s5 = new javax.swing.JSeparator();
        signup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(990, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitlebar.setBackground(new java.awt.Color(0, 0, 0));
        pnlTitlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTitlebarMouseDragged(evt);
            }
        });
        pnlTitlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTitlebarMousePressed(evt);
            }
        });
        pnlTitlebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png"))); // NOI18N
        exitLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLoginMouseClicked(evt);
            }
        });
        pnlTitlebar.add(exitLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, -1));

        minLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/expand.png"))); // NOI18N
        minLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minLoginMouseClicked(evt);
            }
        });
        pnlTitlebar.add(minLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        pnlTitlebar.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(pnlTitlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 35));

        pnl_overlay.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnl_overlayLayout = new javax.swing.GroupLayout(pnl_overlay);
        pnl_overlay.setLayout(pnl_overlayLayout);
        pnl_overlayLayout.setHorizontalGroup(
            pnl_overlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        pnl_overlayLayout.setVerticalGroup(
            pnl_overlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 390, 560));
        getContentPane().add(imgRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 34, 390, 560));

        pnlRegister.setBackground(new java.awt.Color(32, 33, 35));
        pnlRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arvo", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO");
        pnlRegister.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 270, 60));

        nameL.setFont(new java.awt.Font("Arvo", 0, 18)); // NOI18N
        nameL.setForeground(new java.awt.Color(57, 113, 177));
        nameL.setText("Nombre:");
        pnlRegister.add(nameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        nameR.setBackground(new java.awt.Color(32, 33, 35));
        nameR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nameR.setForeground(new java.awt.Color(255, 255, 255));
        nameR.setBorder(null);
        nameR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRActionPerformed(evt);
            }
        });
        pnlRegister.add(nameR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 310, 30));

        s1.setOpaque(true);
        pnlRegister.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 310, -1));

        emailL.setFont(new java.awt.Font("Arvo", 0, 18)); // NOI18N
        emailL.setForeground(new java.awt.Color(57, 113, 177));
        emailL.setText("e-Mail:");
        pnlRegister.add(emailL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, 40));

        emailR.setBackground(new java.awt.Color(32, 33, 35));
        emailR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        emailR.setForeground(new java.awt.Color(255, 255, 255));
        emailR.setBorder(null);
        emailR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailRActionPerformed(evt);
            }
        });
        pnlRegister.add(emailR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 310, 30));

        s2.setOpaque(true);
        pnlRegister.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 310, -1));

        psswdL.setFont(new java.awt.Font("Arvo", 0, 18)); // NOI18N
        psswdL.setForeground(new java.awt.Color(57, 113, 177));
        psswdL.setText("Contraseña:");
        pnlRegister.add(psswdL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 130, 40));

        psswdR.setBackground(new java.awt.Color(32, 33, 35));
        psswdR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        psswdR.setForeground(new java.awt.Color(255, 255, 255));
        psswdR.setBorder(null);
        psswdR.setEchoChar('\u25CF');
        pnlRegister.add(psswdR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 310, 30));

        s3.setOpaque(true);
        pnlRegister.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 310, -1));

        phoneL.setFont(new java.awt.Font("Arvo", 0, 18)); // NOI18N
        phoneL.setForeground(new java.awt.Color(57, 113, 177));
        phoneL.setText("Teléfono:");
        pnlRegister.add(phoneL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 130, 40));

        phoneR.setBackground(new java.awt.Color(32, 33, 35));
        phoneR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        phoneR.setForeground(new java.awt.Color(255, 255, 255));
        phoneR.setBorder(null);
        phoneR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneRActionPerformed(evt);
            }
        });
        pnlRegister.add(phoneR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 240, 30));

        s4.setOpaque(true);
        pnlRegister.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 240, -1));

        jComboBox1.setBackground(new java.awt.Color(32, 33, 35));
        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+1", "+51", "+52", "+54" }));
        jComboBox1.setBorder(null);
        pnlRegister.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 65, 40));

        postalL.setFont(new java.awt.Font("Arvo", 0, 18)); // NOI18N
        postalL.setForeground(new java.awt.Color(57, 113, 177));
        postalL.setText("Postal:");
        pnlRegister.add(postalL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 130, 40));

        postalR.setBackground(new java.awt.Color(32, 33, 35));
        postalR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        postalR.setForeground(new java.awt.Color(255, 255, 255));
        postalR.setBorder(null);
        postalR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalRActionPerformed(evt);
            }
        });
        pnlRegister.add(postalR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, 30));

        s5.setOpaque(true);
        pnlRegister.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 110, -1));

        signup.setBackground(new java.awt.Color(51, 102, 255));
        signup.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("SIGN UP");
        pnlRegister.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 140, 50));

        getContentPane().add(pnlRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLoginMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLoginMouseClicked

    private void minLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minLoginMouseClicked
        // TODO add your handling code here:
        this.setState(ArtistView.ICONIFIED);
    }//GEN-LAST:event_minLoginMouseClicked

    private void pnlTitlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitlebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnlTitlebarMouseDragged

    private void pnlTitlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitlebarMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnlTitlebarMousePressed

    private void nameRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRActionPerformed

    private void emailRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailRActionPerformed

    private void phoneRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneRActionPerformed

    private void postalRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postalRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField emailR;
    private javax.swing.JLabel exitLogin;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel imgRegister;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel minLogin;
    private javax.swing.JLabel nameL;
    private javax.swing.JTextField nameR;
    private javax.swing.JLabel phoneL;
    private javax.swing.JTextField phoneR;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPanel pnlTitlebar;
    private javax.swing.JPanel pnl_overlay;
    private javax.swing.JLabel postalL;
    private javax.swing.JTextField postalR;
    private javax.swing.JLabel psswdL;
    private javax.swing.JPasswordField psswdR;
    private javax.swing.JSeparator s1;
    private javax.swing.JSeparator s2;
    private javax.swing.JSeparator s3;
    private javax.swing.JSeparator s4;
    private javax.swing.JSeparator s5;
    private javax.swing.JButton signup;
    // End of variables declaration//GEN-END:variables
}
