/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aop;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Noe
 */
public class SearchView extends javax.swing.JFrame {

    /**
     * Creates new form SearchView
     */
    int xx, xy;
    
    public SearchView() {
        initComponents();
        
        pnl_overlay.setBackground(new Color(0,0,0,200));
        ImageIcon head = new ImageIcon(getClass().getResource("/images/imgSearch.jpeg"));
        imgSearch.setIcon(scaleImageFill(head, imgSearch));
        
    }

    // Escalando Imagenes
    public ImageIcon scaleImageFill(ImageIcon imgi, JLabel jl){
        int iconWidth = imgi.getIconWidth();
        int iconHeight = imgi.getIconHeight();
        
        double scaleFactor = Math.min(1d, getScaleFactorToFill(new Dimension(iconWidth, iconHeight), jl.getSize()));

        int scaleWidth = (int) Math.round(iconWidth * scaleFactor);
        int scaleHeight = (int) Math.round(iconHeight * scaleFactor);

        Image scaled = imgi.getImage().getScaledInstance(scaleWidth, scaleHeight, Image.SCALE_SMOOTH);
        ImageIcon iconf = new ImageIcon(scaled);
        return iconf;
    }
    
    public double getScaleFactor(int iMasterSize, int iTargetSize) {
        double dScale = 1;
        if (iMasterSize > iTargetSize) {
            dScale = (double) iTargetSize / (double) iMasterSize;
        } else {
            dScale = (double) iTargetSize / (double) iMasterSize;
        }
        return dScale;
    }

    public double getScaleFactorToFit(Dimension original, Dimension toFit) {
        double dScale = 1d;
        if (original != null && toFit != null) {
            double dScaleWidth = getScaleFactor(original.width, toFit.width);
            double dScaleHeight = getScaleFactor(original.height, toFit.height);

            dScale = Math.min(dScaleHeight, dScaleWidth);
        }
        return dScale;
    }
    
    public double getScaleFactorToFill(Dimension masterSize, Dimension targetSize) {
        double dScaleWidth = getScaleFactor(masterSize.width, targetSize.width);
        double dScaleHeight = getScaleFactor(masterSize.height, targetSize.height);

        double dScale = Math.max(dScaleHeight, dScaleWidth);

        return dScale;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitlebar = new javax.swing.JPanel();
        exitLogin = new javax.swing.JLabel();
        minLogin = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        pnl_overlay = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        imgSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitlebar.setBackground(new java.awt.Color(0, 0, 0));
        pnlTitlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTitlebarMouseDragged(evt);
            }
        });
        pnlTitlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTitlebarMousePressed(evt);
            }
        });
        pnlTitlebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png"))); // NOI18N
        exitLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLoginMouseClicked(evt);
            }
        });
        pnlTitlebar.add(exitLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, -1));

        minLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/expand.png"))); // NOI18N
        minLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minLoginMouseClicked(evt);
            }
        });
        pnlTitlebar.add(minLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        pnlTitlebar.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(pnlTitlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 35));

        pnl_overlay.setBackground(new java.awt.Color(0, 0, 0));
        pnl_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        pnl_overlay.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 155, 40, 40));

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pnl_overlay.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 700, 50));

        getContentPane().add(pnl_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 990, 560));
        getContentPane().add(imgSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 990, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLoginMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLoginMouseClicked

    private void minLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minLoginMouseClicked
        // TODO add your handling code here:
        this.setState(ArtistView.ICONIFIED);
    }//GEN-LAST:event_minLoginMouseClicked

    private void pnlTitlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitlebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnlTitlebarMouseDragged

    private void pnlTitlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitlebarMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnlTitlebarMousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitLogin;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel imgSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel minLogin;
    private javax.swing.JPanel pnlTitlebar;
    private javax.swing.JPanel pnl_overlay;
    // End of variables declaration//GEN-END:variables
}
